"""add metadata tables

Revision ID: 1ee1ec15f1a8
Revises: 8943572f1891
Create Date: 2026-04-12 16:30:37.801882

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autonomous_trading_platform.storage.sor.models.helpers.sa_types import UTCDateTimeType

# revision identifiers, used by Alembic.
revision: str = "1ee1ec15f1a8"
down_revision: str | Sequence[str] | None = "8943572f1891"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checksums",
        sa.Column("checksum_id", sa.String(length=64), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_path", sa.String(length=255), nullable=False),
        sa.Column("checksum_algorithm", sa.String(length=32), nullable=False),
        sa.Column("checksum_value", sa.String(length=128), nullable=False),
        sa.Column("created_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("checksum_id", name=op.f("pk_checksums")),
    )
    op.create_table(
        "dataset_versions",
        sa.Column("dataset_version_id", sa.String(length=64), nullable=False),
        sa.Column("dataset_name", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "price_basis",
            postgresql.ENUM("RAW", "ADJUSTED", name="price_basis_enum", create_type=False),
            nullable=True,
        ),
        sa.Column(
            "interval",
            postgresql.ENUM(
                "ONE_MIN",
                "FIVE_MIN",
                "FIFTEEN_MIN",
                "ONE_HOUR",
                "ONE_DAY",
                name="bar_interval_enum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("dataset_version_id", name=op.f("pk_dataset_versions")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("ingestion_run_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("run_timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column(
            "run_type",
            postgresql.ENUM(
                "BACKTEST",
                "PAPER",
                "LIVE",
                "SHADOW",
                "INGESTION",
                name="run_type_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("dataset_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("completed_at", UTCDateTimeType(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("file_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ingestion_run_id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "missing_bar_incidents",
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("bar_timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=64), nullable=True),
        sa.Column("incident_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("created_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("resolved_flag", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("incident_id", name=op.f("pk_missing_bar_incidents")),
    )
    op.create_table(
        "symbol_date_coverages",
        sa.Column("coverage_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("expected_bar_count", sa.Integer(), nullable=False),
        sa.Column("actual_bar_count", sa.Integer(), nullable=False),
        sa.Column("completeness_status", sa.String(length=32), nullable=False),
        sa.Column("gap_summary", sa.String(), nullable=True),
        sa.Column("updated_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("coverage_id", name=op.f("pk_symbol_date_coverages")),
    )
    op.alter_column(
        "audit_logs",
        "event_metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs",
        "event_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_table("symbol_date_coverages")
    op.drop_table("missing_bar_incidents")
    op.drop_table("ingestion_runs")
    op.drop_table("dataset_versions")
    op.drop_table("checksums")
    # ### end Alembic commands ###
