"""add audit_logs table

Revision ID: da2aa2397611
Revises: e62e75b1c021
Create Date: 2026-03-10 19:07:15.234142

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da2aa2397611"
down_revision: str | Sequence[str] | None = "e62e75b1c021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_position_snapshot_items_snapshot_symbol",
        "position_snapshot_items",
        ["snapshot_id", "symbol"],
    )
    op.alter_column("run_manifests", "random_seed", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("run_manifests", "random_seed", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(
        "uq_position_snapshot_items_snapshot_symbol", "position_snapshot_items", type_="unique"
    )
    # ### end Alembic commands ###
