"""init schema

Revision ID: e62e75b1c021
Revises:
Create Date: 2026-03-03 20:47:11.909207

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autonomous_trading_platform.storage.sor.models.helpers.sa_types import (
    MoneyType,
    QuantityType,
    UTCDateTimeType,
)

# revision identifiers, used by Alembic.
revision: str = "e62e75b1c021"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker_orders",
        sa.Column("broker_order_id", sa.String(length=64), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("broker", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="side_enum"), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="order_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "time_in_force",
            sa.Enum("DAY", "GTC", "IOC", "FOK", name="time_in_force_enum"),
            nullable=False,
        ),
        sa.Column("extended_hours", sa.Boolean(), nullable=False),
        sa.Column("qty", QuantityType(precision=18, scale=9), nullable=True),
        sa.Column("notional", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("limit_price", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("stop_price", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "SUBMITTED",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELED",
                "REJECTED",
                name="order_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", UTCDateTimeType(timezone=True), nullable=True),
        sa.Column("updated_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("filled_qty", QuantityType(precision=18, scale=9), nullable=False),
        sa.Column("avg_fill_price", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("raw_broker_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("requested_qty", QuantityType(precision=18, scale=9), nullable=True),
        sa.PrimaryKeyConstraint("broker_order_id", name=op.f("pk_broker_orders")),
    )
    op.create_table(
        "cash_snapshots",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("cash", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("buying_power", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("reserved_cash", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("equity", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column(
            "source",
            sa.Enum("LEDGER", "BROKER_RECONCILED", name="order_source_enum"),
            nullable=False,
        ),
        sa.Column("capital_bucket", MoneyType(precision=18, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_cash_snapshots")),
    )
    op.create_table(
        "corporate_actions",
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "CASH_DIVIDEND",
                "STOCK_DIVIDEND",
                "SPLIT_FORWARD",
                "SPLIT_REVERSE",
                "SPINOFF",
                "MERGER_CASH",
                "MERGER_STOCK",
                "NAME_CHANGE",
                name="corporate_action_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("announced_date", sa.Date(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("payable_date", sa.Date(), nullable=True),
        sa.Column("split_ratio", sa.Float(), nullable=True),
        sa.Column("cash_amount", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=64), nullable=False),
        sa.Column("new_symbol", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("action_id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint(
            "symbol",
            "action_type",
            "effective_date",
            "source",
            name="uq_corporate_actions_symbol_type_date_source",
        ),
    )
    op.create_table(
        "fills",
        sa.Column("fill_id", sa.String(length=64), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="side_enum"), nullable=False),
        sa.Column("quantity", QuantityType(precision=18, scale=9), nullable=False),
        sa.Column("price", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("fees", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column(
            "liquidity", sa.Enum("MAKER", "TAKER", name="liquidity_side_enum"), nullable=True
        ),
        sa.Column("venue", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("fill_id", name=op.f("pk_fills")),
    )
    op.create_table(
        "market_bars",
        sa.Column("bar_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("end_timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column(
            "interval",
            sa.Enum(
                "ONE_MIN",
                "FIVE_MIN",
                "FIFTEEN_MIN",
                "ONE_HOUR",
                "ONE_DAY",
                name="bar_interval_enum",
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("open", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("high", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("low", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("close", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("vwap", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("trade_count", sa.Integer(), nullable=True),
        sa.Column(
            "price_basis", sa.Enum("RAW", "ADJUSTED", name="price_basis_enum"), nullable=False
        ),
        sa.Column("adjustment_factor", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("quality_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("bar_id", name=op.f("pk_market_bars")),
        sa.UniqueConstraint(
            "symbol",
            "interval",
            "timestamp",
            "price_basis",
            name="uq_market_bars_symbol_interval_ts_price_basis",
        ),
    )
    op.create_table(
        "order_intents",
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("bar_timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="side_enum"), nullable=False),
        sa.Column("qty", QuantityType(precision=18, scale=9), nullable=True),
        sa.Column("notional", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="order_type_enum"),
            nullable=False,
        ),
        sa.Column("limit_price", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("stop_price", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column(
            "time_in_force",
            sa.Enum("DAY", "GTC", "IOC", "FOK", name="time_in_force_enum"),
            nullable=False,
        ),
        sa.Column("extended_hours", sa.Boolean(), nullable=False),
        sa.Column("client_order_id", sa.String(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("intent_id", name=op.f("pk_order_intents")),
        sa.UniqueConstraint(
            "run_id", "idempotency_key", name="uq_order_intents_run_id_idempotency_key"
        ),
    )
    op.create_table(
        "position_snapshots",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum("LEDGER", "BROKER_RECONCILED", name="order_source_enum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_position_snapshots")),
        sa.UniqueConstraint(
            "run_id", "timestamp", "source", name="uq_position_snapshots_run_ts_source"
        ),
    )
    op.create_table(
        "risk_snapshots",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("gross_exposure", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("net_exposure", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column("leverage", sa.Float(), nullable=False),
        sa.Column("drawdown_pct", sa.Float(), nullable=True),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("utilization", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("block_reasons", postgresql.ARRAY(sa.String(length=64)), nullable=True),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_risk_snapshots")),
    )
    op.create_table(
        "run_manifests",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "run_type",
            sa.Enum("BACKTEST", "PAPER", "LIVE", "SHADOW", name="run_type_enum"),
            nullable=False,
        ),
        sa.Column("created_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("environment", sa.String(), nullable=False),
        sa.Column("broker", sa.String(), nullable=False),
        sa.Column("broker_account_id", sa.String(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("strategy_version", sa.String(), nullable=False),
        sa.Column("strategy_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("capital_bucket", MoneyType(precision=18, scale=6), nullable=False),
        sa.Column(
            "interval",
            sa.Enum(
                "ONE_MIN",
                "FIVE_MIN",
                "FIFTEEN_MIN",
                "ONE_HOUR",
                "ONE_DAY",
                name="bar_interval_enum",
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("dataset_version", sa.String(), nullable=False),
        sa.Column("universe_version", sa.String(), nullable=False),
        sa.Column("cost_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fill_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("git_commit", sa.String(), nullable=False),
        sa.Column("docker_image", sa.String(), nullable=True),
        sa.Column("python_version", sa.String(), nullable=True),
        sa.Column("dependency_lock_hash", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_manifests")),
    )
    op.create_table(
        "signals",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("bar_timestamp", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("BUY", "SELL", "FLAT", name="signal_direction_enum"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("target_position", QuantityType(precision=18, scale=9), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("signal_id", name=op.f("pk_signals")),
        sa.UniqueConstraint(
            "run_id",
            "bar_timestamp",
            "symbol",
            "strategy_id",
            name="uq_signals_run_bar_symbol_strategy",
        ),
    )
    op.create_table(
        "universe_snapshots",
        sa.Column("universe_id", sa.String(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("effective_start", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("effective_end", UTCDateTimeType(timezone=True), nullable=True),
        sa.Column("symbols", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("built_at", UTCDateTimeType(timezone=True), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("universe_id", name=op.f("pk_universe_snapshots")),
    )
    op.create_table(
        "position_snapshot_items",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("quantity", QuantityType(precision=18, scale=9), nullable=False),
        sa.Column("avg_cost", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("market_price", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("market_value", MoneyType(precision=18, scale=6), nullable=True),
        sa.Column("unrealized_pnl", MoneyType(precision=18, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["position_snapshots.snapshot_id"],
            name=op.f("fk_position_snapshot_items_snapshot_id_position_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "symbol", name=op.f("pk_position_snapshot_items")),
        sa.UniqueConstraint(
            "snapshot_id", "symbol", name="uq_position_snapshot_items_snapshot_symbol"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("position_snapshot_items")
    op.drop_table("universe_snapshots")
    op.drop_table("signals")
    op.drop_table("run_manifests")
    op.drop_table("risk_snapshots")
    op.drop_table("position_snapshots")
    op.drop_table("order_intents")
    op.drop_table("market_bars")
    op.drop_table("fills")
    op.drop_table("corporate_actions")
    op.drop_table("cash_snapshots")
    op.drop_table("broker_orders")
    # ### end Alembic commands ###
