"""add market_session to market_bars

Revision ID: fbc5d464a623
Revises: da2aa2397611
Create Date: 2026-03-25 16:27:01.507271

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autonomous_trading_platform.storage.sor.models.helpers.sa_types import UTCDateTimeType

# revision identifiers, used by Alembic.
revision: str = "fbc5d464a623"
down_revision: str | Sequence[str] | None = "da2aa2397611"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticker_lifecycle_events_symbol"), table_name="ticker_lifecycle_events")
    op.drop_table("ticker_lifecycle_events")
    op.drop_table("strategy_runtime_states")
    op.drop_table("audit_logs")
    op.drop_table("tracked_orders")
    op.add_column(
        "market_bars",
        sa.Column(
            "market_session",
            sa.Enum("PREMARKET", "REGULAR", "POSTMARKET", "OVERNIGHT", name="market_session_enum"),
            nullable=False,
        ),
    )
    op.add_column(
        "run_manifests", sa.Column("bar_timestamp", UTCDateTimeType(timezone=True), nullable=True)
    )
    op.add_column("run_manifests", sa.Column("status", sa.String(), nullable=True))
    op.add_column("run_manifests", sa.Column("current_step", sa.String(), nullable=True))
    op.add_column("run_manifests", sa.Column("last_successful_step", sa.String(), nullable=True))
    op.add_column("run_manifests", sa.Column("error_message", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("run_manifests", "error_message")
    op.drop_column("run_manifests", "last_successful_step")
    op.drop_column("run_manifests", "current_step")
    op.drop_column("run_manifests", "status")
    op.drop_column("run_manifests", "bar_timestamp")
    op.drop_column("market_bars", "market_session")
    op.create_table(
        "tracked_orders",
        sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("intent_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("run_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("strategy_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("broker_order_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "current_status",
            postgresql.ENUM(
                "NEW",
                "SUBMITTED",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELED",
                "REJECTED",
                name="tracked_order_status_enum",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "previous_filled_qty",
            sa.NUMERIC(precision=18, scale=9),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "previous_avg_fill_price",
            sa.NUMERIC(precision=18, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_open", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_tracked_orders")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("event_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("run_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("event_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("component", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("event_timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "event_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "strategy_runtime_states",
        sa.Column("strategy_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "current_state",
            postgresql.ENUM(
                "IDLE",
                "SIGNALLED",
                "PENDING",
                "IN_POSITION",
                "EXIT_PENDING",
                "COOLDOWN",
                name="strategy_runtime_state_enum",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_signal_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_transition_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "cooldown_until",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("strategy_id", name=op.f("pk_strategy_runtime_states")),
    )
    op.create_table(
        "ticker_lifecycle_events",
        sa.Column("event_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "effective_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("new_symbol", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("successor_symbol", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_ticker_lifecycle_events")),
    )
    op.create_index(
        op.f("ix_ticker_lifecycle_events_symbol"),
        "ticker_lifecycle_events",
        ["symbol"],
        unique=False,
    )
    # ### end Alembic commands ###
